/**
 * @file page.tsx
 * @description
 * This server component is the marketing homepage (the main landing page) for BadBeats.org.
 * We've refactored it to link to important pages we've built:
 *   - /picks (AI Picks) for pro members
 *
 * Key Features:
 * - A hero section that introduces BadBeats.org
 * - A features section (tech stack highlights) for demonstration
 * - Additional calls to action linking to the new pages
 * - A disclaimers & CTA block at the end encouraging sign-ups
 *
 * Implementation Details:
 * - This is a Next.js server component using "use server"
 * - The hero and features components are imported from @/components/landing
 * - We have added content to direct users to the new site pages
 *
 * Notes:
 * - If the user is not signed in, they can sign up or read about the site
 * - If the user is signed in, they can go to the user picks page or see the AI picks if they're pro
 * - Additional marketing calls to action have been placed
 */

"use server"

import { Suspense } from "react"
import { auth } from "@clerk/nextjs/server"
import { FeaturesSection } from "@/components/landing/features"
import { HeroSection } from "@/components/landing/hero"

/**
 * The main marketing landing page for BadBeats.org.
 *
 * This page displays:
 * - A hero banner introducing the brand
 * - A features section listing our tech stack
 * - Some disclaimers about gambling and how to sign up
 *
 * @returns JSX for the landing page
 */
export default async function HomePage() {
  const { userId } = await auth()

  return (
    <Suspense fallback={<div className="p-4">Loading homepage...</div>}>
      <div className="pb-20">
        {/* Hero section from components/landing/hero.tsx */}
        <HeroSection />

        {/* Tech Stack Features from components/landing/features.tsx}
        {<FeaturesSection /> */}

        {/* 
          New Section: Tying in the recently built pages:
          - AI Picks (Pro users only)
        */}
        <section className="mx-auto mt-12 max-w-5xl px-4 text-center">
          <h2 className="mb-4 text-3xl font-bold">
            Explore Our Latest Features
          </h2>

          <p className="text-muted-foreground mx-auto mb-8 max-w-3xl text-lg">
            Ready to take your sports betting experience to the next level?
            We’ve added new pages to help you stay on top of your picks and
            leverage AI insights.
          </p>

          <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
            {/* Card for AI Picks */}
            <div className="rounded-md border p-4 shadow-sm">
              <h3 className="mb-2 text-xl font-semibold">AI Picks</h3>
              <p className="text-muted-foreground mb-4 text-sm">
                See today's NBA spread picks generated by our cutting edge
                Generative AI model. (Pro membership required)
              </p>
              <a
                href="/picks"
                className="inline-block rounded bg-blue-500 px-4 py-2 text-sm font-medium text-white hover:bg-blue-600"
              >
                View AI Picks
              </a>
            </div>
          </div>
        </section>

        {/* Gambling disclaimers & CTA */}
        <section className="mx-auto mt-20 max-w-4xl px-4 text-center">
          <h2 className="mb-2 text-2xl font-bold">Important Disclaimer</h2>
          <p className="text-muted-foreground mx-auto max-w-3xl text-sm">
            All picks and data on BadBeats.org are provided for informational
            purposes only. They do not constitute gambling advice. Sports
            betting involves significant risk; please bet responsibly, and if
            you feel you have a gambling problem, seek professional help. Must
            be of legal age in your jurisdiction.
          </p>
        </section>

        <section className="mx-auto mt-10 max-w-5xl px-4 text-center">
          <h3 className="mb-4 text-xl font-semibold">Ready to Get Started?</h3>
          {userId ? (
            <div className="mb-2 text-sm">
              You’re already signed in! Head over to{" "}
              <a href="/picks" className="text-blue-500 hover:underline">
                AI Picks
              </a>{" "}
              to see today’s recommendations, or{" "}
            </div>
          ) : (
            <div className="mb-2 text-sm">
              <p className="mb-4">
                Upgrade to Pro for full access to AI picks!
              </p>
              <div className="space-x-2">
                <a
                  href="/signup"
                  className="inline-block rounded bg-blue-500 px-4 py-2 text-sm font-medium text-white hover:bg-blue-600"
                >
                  Sign Up
                </a>
                <a
                  href="/login"
                  className="inline-block rounded border border-blue-500 px-4 py-2 text-sm font-medium text-blue-500 hover:bg-blue-500 hover:text-white"
                >
                  Log In
                </a>
              </div>
            </div>
          )}
        </section>
      </div>
    </Suspense>
  )
}
